from sqlalchemy import Column, Integer, String, DateTime, Float, ForeignKey, Boolean, Text
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy.orm import relationship
from datetime import datetime

Base = declarative_base()

class Student(Base):
    """
    Student model representing enrolled students.
    """
    __tablename__ = "students"
    
    id = Column(Integer, primary_key=True, index=True)
    student_id = Column(String(50), unique=True, index=True, nullable=False)
    first_name = Column(String(100), nullable=False)
    last_name = Column(String(100), nullable=False)
    email = Column(String(255), unique=True, index=True)
    phone = Column(String(20))
    enrollment_date = Column(DateTime, default=datetime.utcnow)
    is_active = Column(Boolean, default=True)
    
    # Relationships
    attendance_records = relationship("AttendanceRecord", back_populates="student", cascade="all, delete-orphan")
    face_embeddings = relationship("FaceEmbedding", back_populates="student", cascade="all, delete-orphan")

    def __repr__(self):
        return f"<Student(id={self.student_id}, name={self.first_name} {self.last_name})>"

class FaceEmbedding(Base):
    """
    Storage for facial embeddings (mathematical vectors) generated by deepface.
    """
    __tablename__ = "face_embeddings"
    
    id = Column(Integer, primary_key=True, index=True)
    student_id = Column(Integer, ForeignKey("students.id"), nullable=False)
    embedding_vector = Column(Text, nullable=False)  # JSON serialized numpy array (512-dim for Facenet512)
    created_at = Column(DateTime, default=datetime.utcnow)
    image_path = Column(String(255))
    model_name = Column(String(50), default="Facenet512")  # Track which model generated this embedding
    
    student = relationship("Student", back_populates="face_embeddings")

    def __repr__(self):
        return f"<FaceEmbedding(student_id={self.student_id}, model={self.model_name})>"

class AttendanceRecord(Base):
    """
    Records of student attendance markings.
    """
    __tablename__ = "attendance_records"
    
    id = Column(Integer, primary_key=True, index=True)
    student_id = Column(Integer, ForeignKey("students.id"), nullable=False)
    timestamp = Column(DateTime, default=datetime.utcnow, index=True)
    confidence_score = Column(Float)
    camera_id = Column(String(50), default="main_camera")
    image_path = Column(String(255))  # Snapshot of the recognition event
    status = Column(String(20), default="present")  # present, late, excused
    
    student = relationship("Student", back_populates="attendance_records")

    def __repr__(self):
        return f"<AttendanceRecord(student_id={self.student_id}, time={self.timestamp}, status={self.status})>"

class UnknownFace(Base):
    """
    Logs of unrecognized faces for administrative review and dataset expansion.
    """
    __tablename__ = "unknown_faces"
    
    id = Column(Integer, primary_key=True, index=True)
    timestamp = Column(DateTime, default=datetime.utcnow, index=True)
    image_path = Column(String(255))
    reviewed = Column(Boolean, default=False)
    confidence = Column(Float)  # Highest confidence match (though below threshold)
    
    def __repr__(self):
        return f"<UnknownFace(id={self.id}, time={self.timestamp}, reviewed={self.reviewed})>"
